// 회의록 작업관리 프로토타입 샘플 데이터 (5차 고도화)
export const MEETING_SAMPLES = [
  {
    id: 'PROTO-MTG-001',
    servCd: 'PROTO-MTG-001',
    entNm: '서울시의회',
    servTitle: '제384회 임시회 제1차 운영위원회 회의록',
    membNm: '박진수',
    bssType: '회의록',
    bssTypeName: '회의록',
    totalPlayTm: '03:42:15',
    totalDuration: '222분',
    overallStatus: 'WORKING',
    regDttm: '2026-06-01 10:00',
    dueDate: '2026-06-25',
    actualDeliveryDate: '-',
    remark: '한글 문서 납품, 공문서 형식 적용',
    cnlYn: 'N',
    orgNm: '서울특별시의회',
    managerNm: '김철수',
    deliveryFormats: 'HWP',
    specialNote: '한글 문서 납품, 공문서 형식 적용',
    internalMemo: '1부 전사·검수 완료. 2부 전사 진행중.',
    statusHistory: [
      { date: '2026-06-01', label: '접수' },
      { date: '2026-06-01', label: '파일등록' },
      { date: '2026-06-02', label: '배정완료' },
      { date: '2026-06-02', label: '작업중 전환' },
    ],
    protoPath: '/soribaro/enterprise/meeting-proto/PROTO-MTG-001',
    files: [
      { fileNo: 1, fileName: '제1차_운영위원회_1부.wav', duration: '01:45:30', size: '980 MB', uploadDttm: '2026-06-01' },
      { fileNo: 2, fileName: '제1차_운영위원회_2부.wav', duration: '01:56:45', size: '1.1 GB', uploadDttm: '2026-06-01' },
    ],
    assignments: [
      { fileNo: 1, fileName: '제1차_운영위원회_1부.wav', worker: '김미래', role: '전사', assignDttm: '2026-06-02', status: '완료' },
      { fileNo: 2, fileName: '제1차_운영위원회_2부.wav', worker: '이세진', role: '전사', assignDttm: '2026-06-02', status: '작업중' },
      { fileNo: 1, fileName: '제1차_운영위원회_1부.wav', worker: '최정원', role: '검수', assignDttm: '2026-06-08', status: '완료' },
    ],
    manuals: [
      { name: '서울시의회 회의록 작성 지침 2026', type: '매뉴얼', appliedDate: '2026-06-01' },
      { name: '서울시의회 위원 명부 및 직책 용어집', type: '용어집', appliedDate: '2026-06-01' },
      { name: '의회 전문용어 사전 (행정·입법)', type: '용어집', appliedDate: '2026-06-02' },
    ],
    workProgress: [
      { fileNo: 1, fileName: '제1차_운영위원회_1부.wav', worker: '김미래', progress: 100, lastWork: '2026-06-07 17:00' },
      { fileNo: 2, fileName: '제1차_운영위원회_2부.wav', worker: '이세진', progress: 55, lastWork: '2026-06-11 16:00' },
    ],
    qcScore: 88.5,
    qcResults: [
      { errorType: '발언자 오인식', count: 5, severity: '높음', example: '"의원" → "위원장" 표기 오류' },
      { errorType: '전문용어 오류', count: 9, severity: '중간', example: '조례 번호 표기 방식 불일치' },
      { errorType: '맞춤법', count: 4, severity: '낮음', example: '띄어쓰기·맞춤법 등' },
    ],
    deliveries: [
      { no: 1, dueDate: '2026-06-25', deliveredDate: '-', format: 'HWP', files: '전체 회의록', status: '납품예정' },
    ],
    settlement: {
      status: '정산전',
      items: [
        { worker: '김미래', role: '전사', amount: 315000, taxRate: 3.3, netAmount: 304605 },
        { worker: '이세진', role: '전사', amount: 350100, taxRate: 3.3, netAmount: 338547 },
        { worker: '최정원', role: '검수', amount: 63000, taxRate: 3.3, netAmount: 60921 },
      ],
    },
    history: [
      { dttm: '2026-06-01 10:00', actor: '박진수(의뢰인)', event: '프로젝트 의뢰 등록', detail: '운영위원회 회의록 2부 전사 의뢰' },
      { dttm: '2026-06-01 11:00', actor: '관리자', event: '파일 업로드 완료', detail: 'wav 파일 2개 업로드' },
      { dttm: '2026-06-02 09:00', actor: '관리자', event: '작업 배정', detail: '전사 2명, 검수 1명 배정' },
      { dttm: '2026-06-07 17:00', actor: '김미래', event: '1부 전사 완료', detail: '' },
      { dttm: '2026-06-08 09:30', actor: '관리자', event: '1부 검수 배정', detail: '최정원 검수 시작' },
      { dttm: '2026-06-09 16:00', actor: '최정원', event: '1부 검수 완료', detail: '' },
    ],
    memos: [
      { dttm: '2026-06-03 10:00', author: '관리자', content: '회의 중 특정 발언자의 발음이 불분명한 구간 다수. 전사자에게 [청취불명] 처리 기준 별도 안내 완료.' },
    ],
  },
  {
    id: 'PROTO-MTG-002',
    servCd: 'PROTO-MTG-002',
    entNm: '서울특별시교육청',
    servTitle: '학교폭력 예방 협의회 정기 회의록',
    membNm: '오승환',
    bssType: '회의록',
    bssTypeName: '회의록',
    totalPlayTm: '02:18:50',
    totalDuration: '138분',
    overallStatus: 'CHECKING',
    regDttm: '2026-05-28 13:00',
    dueDate: '2026-06-18',
    actualDeliveryDate: '-',
    remark: 'PDF 납품, 기관 공문서 포맷 적용',
    cnlYn: 'N',
    orgNm: '서울특별시교육청',
    managerNm: '이민호',
    deliveryFormats: 'PDF',
    specialNote: 'PDF 납품, 기관 공문서 포맷 적용',
    internalMemo: '전사 완료, 검수 진행중.',
    statusHistory: [
      { date: '2026-05-28', label: '접수' },
      { date: '2026-05-28', label: '파일등록' },
      { date: '2026-05-29', label: '배정완료' },
      { date: '2026-06-06', label: '검수중 전환' },
    ],
    protoPath: '/soribaro/enterprise/meeting-proto/PROTO-MTG-002',
    files: [
      { fileNo: 1, fileName: '학폭예방_협의회_전체.wav', duration: '02:18:50', size: '1.3 GB', uploadDttm: '2026-05-28' },
    ],
    assignments: [
      { fileNo: 1, fileName: '학폭예방_협의회_전체.wav', worker: '하나경', role: '전사', assignDttm: '2026-05-29', status: '완료' },
      { fileNo: 1, fileName: '학폭예방_협의회_전체.wav', worker: '전민준', role: '검수', assignDttm: '2026-06-06', status: '검수중' },
    ],
    manuals: [
      { name: '교육청 회의록 작성 매뉴얼 v2.0', type: '매뉴얼', appliedDate: '2026-05-28' },
      { name: '교육행정 전문용어 사전', type: '용어집', appliedDate: '2026-05-28' },
    ],
    workProgress: [
      { fileNo: 1, fileName: '학폭예방_협의회_전체.wav', worker: '하나경', progress: 100, lastWork: '2026-06-05 18:00' },
    ],
    qcScore: 93.1,
    qcResults: [
      { errorType: '맞춤법', count: 6, severity: '낮음', example: '교육 관련 용어 표기 혼용' },
      { errorType: '발언자 구분 오류', count: 3, severity: '중간', example: '좌장 vs 위원 발언자 혼용' },
    ],
    deliveries: [
      { no: 1, dueDate: '2026-06-18', deliveredDate: '-', format: 'PDF', files: '전체 회의록', status: '검수중' },
    ],
    settlement: {
      status: '정산전',
      items: [
        { worker: '하나경', role: '전사', amount: 415800, taxRate: 3.3, netAmount: 402078 },
        { worker: '전민준', role: '검수', amount: 83160, taxRate: 3.3, netAmount: 80416 },
      ],
    },
    history: [
      { dttm: '2026-05-28 13:00', actor: '오승환(의뢰인)', event: '프로젝트 의뢰 등록', detail: '학교폭력 협의회 정기 회의록 전사' },
      { dttm: '2026-05-28 15:00', actor: '관리자', event: '파일 업로드 완료', detail: 'wav 파일 1개 업로드' },
      { dttm: '2026-05-29 09:00', actor: '관리자', event: '작업 배정', detail: '전사 1명(하나경) 배정' },
      { dttm: '2026-06-05 18:00', actor: '하나경', event: '전사 완료', detail: '' },
      { dttm: '2026-06-06 09:00', actor: '관리자', event: '검수 배정', detail: '검수 1명(전민준) 추가 배정' },
    ],
    memos: [],
  },
];
