// 녹취록 작업관리 프로토타입 샘플 데이터 — 회의록과 동일한 구조를 사용하되, 별도 저장소(protoStore._recordingSamples)로 독립 관리한다.
export const RECORDING_SAMPLES = [
  {
    id: 'PROTO-REC-001',
    servCd: 'PROTO-REC-001',
    entNm: '한빛법률사무소',
    servTitle: '한빛법률사무소 계약분쟁 조정회의 녹취록',
    membNm: '정도윤',
    bssType: '녹취록',
    bssTypeName: '녹취록',
    totalPlayTm: '01:12:00',
    totalDuration: '72분',
    overallStatus: 'WORKING',
    subfileStatus: '요청',
    contractType: '현장녹음',
    fixPrice: 254000,
    round: '1회',
    regDttm: '2026-06-18 09:30',
    dueDate: '2026-06-25',
    actualDeliveryDate: '-',
    remark: '',
    cnlYn: 'N',
    orgNm: '한빛법률사무소',
    managerNm: '서다인',
    phone: '010-2231-9087',
    email: 'jdy@hanbit-law.kr',
    deliveryAddress: '04524 서울 중구 세종대로 110, 305호',
    paymentType: '계좌이체',
    recordingDate: '2026-06-17',
    recordingLocation: '사무실 회의실',
    bindingCount: '-',
    speakers: [
      { no: 1, name: '정도윤', feature: '남자, 목소리 낮음' },
      { no: 2, name: '서다인', feature: '여자, 목소리 또렷함' },
    ],
    staffNm: '한지우',
    staffPhone: '010-2231-9087',
    staffEmail: 'hanjw@hanbit-law.kr',
    deliveryFormats: 'HWP',
    specialNote: '(초) 25일 오전까지 제출',
    clientRequest: '발언자 구분을 명확히 표기해 주세요.',
    internalMemo: '',
    statusHistory: [
      { date: '2026-06-18', label: '접수' },
      { date: '2026-06-18', label: '파일등록' },
      { date: '2026-06-18', label: '배정완료' },
      { date: '2026-06-18', label: '작업중 전환' },
    ],
    protoPath: '/soribaro/recording/detail/PROTO-REC-001',
    files: [
      { fileNo: 1, fileName: '계약분쟁_조정회의_1부.wav', duration: '00:36:00', size: '198 MB', uploadDttm: '2026-06-18' },
      { fileNo: 2, fileName: '계약분쟁_조정회의_2부.wav', duration: '00:36:00', size: '201 MB', uploadDttm: '2026-06-18' },
    ],
    assignments: [
      { fileNo: 1, fileName: '계약분쟁_조정회의_1부.wav', worker: '오세훈', role: '전사', assignDttm: '2026-06-18', status: '작업중' },
      { fileNo: 2, fileName: '계약분쟁_조정회의_2부.wav', worker: '오세훈', role: '전사', assignDttm: '2026-06-18', status: '미배정' },
    ],
    manuals: [
      { name: '한빛법률사무소 녹취록 작성 지침', type: '매뉴얼', appliedDate: '2026-06-18' },
    ],
    workProgress: [
      { fileNo: 1, fileName: '계약분쟁_조정회의_1부.wav', worker: '오세훈', progress: 55, lastWork: '2026-06-19 11:00' },
      { fileNo: 2, fileName: '계약분쟁_조정회의_2부.wav', worker: '-', progress: 0, lastWork: '-' },
    ],
    qcScore: null,
    qcResults: [],
    deliveries: [
      { no: 1, dueDate: '2026-06-25', deliveredDate: '-', format: 'HWP', files: '전체 녹취록', status: '납품예정' },
    ],
    settlement: {
      status: '정산대기',
      workerSettled: false,
      companySettled: false,
      items: [
        { worker: '오세훈', role: '전사', amount: 254000, taxRate: 3.3, netAmount: 245618 },
      ],
    },
    history: [
      { dttm: '2026-06-18 09:30', actor: '관리자', event: '프로젝트 의뢰 등록', detail: '계약분쟁 조정회의 녹취록 전사 의뢰' },
      { dttm: '2026-06-18 10:00', actor: '관리자', event: '파일 업로드 완료', detail: 'wav 파일 2개 업로드' },
      { dttm: '2026-06-18 11:00', actor: '관리자', event: '작업 배정', detail: '전사 1명(오세훈) 배정' },
    ],
    memos: [],
  },
  {
    id: 'PROTO-REC-002',
    servCd: 'PROTO-REC-002',
    entNm: '대성건설',
    servTitle: '대성건설 하도급 협의 녹취록',
    membNm: '류지호',
    bssType: '녹취록',
    bssTypeName: '녹취록',
    totalPlayTm: '02:05:00',
    totalDuration: '125분',
    overallStatus: 'CHECKING',
    subfileStatus: '수령',
    contractType: '통화녹음',
    fixPrice: 334000,
    round: '2회',
    regDttm: '2026-06-19 13:00',
    dueDate: '2026-06-21',
    actualDeliveryDate: '-',
    remark: '',
    cnlYn: 'N',
    orgNm: '대성건설',
    managerNm: '류지호',
    phone: '010-8842-1190',
    email: 'ryujh@daesung-cst.co.kr',
    deliveryAddress: '41911 대구 중구 국채보상로 623, 7층',
    paymentType: '신용카드',
    recordingDate: '2026-06-19',
    recordingLocation: '현장 사무소',
    bindingCount: 1,
    speakers: [
      { no: 1, name: '류지호', feature: '남자, 목소리 두꺼움' },
      { no: 2, name: '문가은', feature: '여자, 목소리 얇음' },
    ],
    staffNm: '',
    staffPhone: '',
    staffEmail: '',
    deliveryFormats: 'HWP',
    specialNote: '(검) 21일 오전까지 발송',
    internalMemo: '',
    statusHistory: [
      { date: '2026-06-19', label: '접수' },
      { date: '2026-06-19', label: '파일등록' },
      { date: '2026-06-19', label: '배정완료' },
      { date: '2026-06-19', label: '검수중 전환' },
    ],
    protoPath: '/soribaro/recording/detail/PROTO-REC-002',
    files: [
      { fileNo: 1, fileName: '하도급_협의_전체.wav', duration: '02:05:00', size: '980 MB', uploadDttm: '2026-06-19' },
    ],
    assignments: [
      { fileNo: 1, fileName: '하도급_협의_전체.wav', worker: '문가은', role: '전사', assignDttm: '2026-06-19', status: '완료' },
      { fileNo: 1, fileName: '하도급_협의_전체.wav', worker: '서다인', role: '검수', assignDttm: '2026-06-19', status: '검수중' },
    ],
    manuals: [
      { name: '대성건설 녹취록 작성 지침', type: '매뉴얼', appliedDate: '2026-06-19' },
    ],
    workProgress: [
      { fileNo: 1, fileName: '하도급_협의_전체.wav', worker: '문가은', progress: 100, lastWork: '2026-06-19 20:00' },
    ],
    qcScore: null,
    qcResults: [],
    deliveries: [
      { no: 1, dueDate: '2026-06-21', deliveredDate: '-', format: 'HWP', files: '전체 녹취록', status: '검수중' },
    ],
    settlement: {
      status: '정산대기',
      workerSettled: false,
      companySettled: false,
      items: [
        { worker: '문가은', role: '전사', amount: 80000, taxRate: 3.3, netAmount: 40000 },
        { worker: '서다인', role: '검수', amount: 254000, taxRate: 3.3, netAmount: 254000 },
      ],
    },
    history: [
      { dttm: '2026-06-19 13:00', actor: '관리자', event: '프로젝트 의뢰 등록', detail: '하도급 협의 녹취록 전사 의뢰' },
      { dttm: '2026-06-19 14:00', actor: '관리자', event: '파일 업로드 완료', detail: 'wav 파일 1개 업로드' },
      { dttm: '2026-06-19 15:00', actor: '관리자', event: '작업 배정', detail: '전사 1명(문가은) 배정' },
      { dttm: '2026-06-19 21:00', actor: '문가은', event: '전사 완료', detail: '' },
      { dttm: '2026-06-19 21:30', actor: '관리자', event: '검수 배정', detail: '검수 1명(서다인) 배정' },
    ],
    memos: [],
  },
];
