// 현장속기 작업관리 프로토타입 샘플 데이터
export const STENOGRAPHY_SAMPLES = [
  {
    id: 'PROTO-STG-001',
    servCd: 'PROTO-STG-001',
    entNm: '서울시의회',
    servTitle: '서울시의회 제316회 임시회 현장속기',
    membNm: '박진수',
    bssType: '현장속기',
    bssTypeName: '현장속기',
    totalPlayTm: '3:10',
    totalDuration: '190분',
    overallStatus: 'WORKING',
    subfileStatus: '미요청',
    contractType: '의회',
    round: '제316회',
    regDttm: '2026-06-16 09:00',
    dueDate: '2026-06-18',
    actualDeliveryDate: '-',
    remark: '',
    cnlYn: 'N',
    orgNm: '서울시의회',
    managerNm: '김철수',
    deliveryFormats: 'HWP',
    specialNote: '오전 본회의 속기 우선 납품',
    clientRequest: '의원 발언 중 연단 발언과 자리 발언을 구분하여 작성 부탁드립니다.',
    internalMemo: '',
    statusHistory: [
      { date: '2026-06-16', label: '접수' },
      { date: '2026-06-16', label: '배정완료' },
      { date: '2026-06-16', label: '작업중 전환' },
    ],
    protoPath: '/soribaro/stenography/detail/PROTO-STG-001',
    files: [
      { fileNo: 1, fileName: '316임시회_오전본회의.wav', duration: '1:45', size: '792 MB', uploadDttm: '2026-06-16' },
      { fileNo: 2, fileName: '316임시회_오후본회의.wav', duration: '1:25', size: '638 MB', uploadDttm: '2026-06-16' },
    ],
    assignments: [
      { fileNo: 1, fileName: '316임시회_오전본회의.wav', worker: '홍길동', role: '속기', assignDttm: '2026-06-16', status: '작업중' },
      { fileNo: 2, fileName: '316임시회_오후본회의.wav', worker: '이수진', role: '속기', assignDttm: '2026-06-16', status: '작업중' },
    ],
    manuals: [
      { name: '서울시의회 속기 작성 지침', type: '매뉴얼', appliedDate: '2026-06-16' },
    ],
    workProgress: [
      { fileNo: 1, fileName: '316임시회_오전본회의.wav', worker: '홍길동', progress: 60, lastWork: '2026-06-17 15:00' },
      { fileNo: 2, fileName: '316임시회_오후본회의.wav', worker: '이수진', progress: 35, lastWork: '2026-06-17 14:00' },
    ],
    qcScore: null,
    qcResults: [],
    deliveries: [
      { no: 1, dueDate: '2026-06-18', deliveredDate: '-', format: 'HWP', files: '전체 속기록', status: '납품예정' },
    ],
    settlement: {
      status: '정산대기',
      items: [
        { worker: '홍길동', role: '속기', amount: 520000, taxRate: 3.3, netAmount: 468000 },
        { worker: '이수진', role: '속기', amount: 420000, taxRate: 3.3, netAmount: 378000 },
      ],
    },
    history: [
      { dttm: '2026-06-16 09:00', actor: '관리자', event: '의뢰 등록', detail: '서울시의회 제316회 현장속기 의뢰' },
      { dttm: '2026-06-16 10:00', actor: '관리자', event: '파일 업로드 완료', detail: 'wav 파일 2개 업로드' },
      { dttm: '2026-06-16 11:00', actor: '관리자', event: '작업 배정', detail: '속기사 2명(홍길동, 이수진) 배정' },
    ],
    memos: [],
  },
  {
    id: 'PROTO-STG-002',
    servCd: 'PROTO-STG-002',
    entNm: '경기도의회',
    servTitle: '경기도의회 제380회 정례회 현장속기',
    membNm: '이민호',
    bssType: '현장속기',
    bssTypeName: '현장속기',
    totalPlayTm: '2:45',
    totalDuration: '165분',
    overallStatus: 'CHECKING',
    subfileStatus: '요청',
    contractType: '의회',
    round: '제380회',
    regDttm: '2026-06-17 10:00',
    dueDate: '2026-06-19',
    actualDeliveryDate: '-',
    remark: '',
    cnlYn: 'N',
    orgNm: '경기도의회',
    managerNm: '이민호',
    deliveryFormats: 'HWP',
    specialNote: '19일 오전 9시 이전 납품 필수',
    clientRequest: '교육위원회 회의 속기록 검수 후 제출 요망.',
    internalMemo: '',
    statusHistory: [
      { date: '2026-06-17', label: '접수' },
      { date: '2026-06-17', label: '배정완료' },
      { date: '2026-06-17', label: '작업중 전환' },
      { date: '2026-06-18', label: '검수중 전환' },
    ],
    protoPath: '/soribaro/stenography/detail/PROTO-STG-002',
    files: [
      { fileNo: 1, fileName: '경기도의회_380정례회.wav', duration: '2:45', size: '1.2 GB', uploadDttm: '2026-06-17' },
    ],
    assignments: [
      { fileNo: 1, fileName: '경기도의회_380정례회.wav', worker: '김나리', role: '속기', assignDttm: '2026-06-17', status: '완료' },
      { fileNo: 1, fileName: '경기도의회_380정례회.wav', worker: '박민준', role: '검수', assignDttm: '2026-06-18', status: '검수중' },
    ],
    manuals: [
      { name: '경기도의회 속기 작성 규정', type: '매뉴얼', appliedDate: '2026-06-17' },
    ],
    workProgress: [
      { fileNo: 1, fileName: '경기도의회_380정례회.wav', worker: '김나리', progress: 100, lastWork: '2026-06-18 09:00' },
    ],
    qcScore: null,
    qcResults: [],
    deliveries: [
      { no: 1, dueDate: '2026-06-19', deliveredDate: '-', format: 'HWP', files: '전체 속기록', status: '검수중' },
    ],
    settlement: {
      status: '정산대기',
      items: [
        { worker: '김나리', role: '속기', amount: 480000, taxRate: 3.3, netAmount: 432000 },
        { worker: '박민준', role: '검수', amount: 150000, taxRate: 3.3, netAmount: 135000 },
      ],
    },
    history: [
      { dttm: '2026-06-17 10:00', actor: '관리자', event: '의뢰 등록', detail: '경기도의회 제380회 현장속기 의뢰' },
      { dttm: '2026-06-17 11:00', actor: '관리자', event: '파일 업로드 완료', detail: 'wav 파일 1개 업로드' },
      { dttm: '2026-06-17 12:00', actor: '관리자', event: '작업 배정', detail: '속기사 1명(김나리) 배정' },
      { dttm: '2026-06-18 09:00', actor: '김나리', event: '속기 완료', detail: '' },
      { dttm: '2026-06-18 09:30', actor: '관리자', event: '검수 배정', detail: '검수 1명(박민준) 배정' },
    ],
    memos: [],
  },
];
